### ISSUE TITLE
Kubeflow Notebooks: Cannot select `Allow access to Kubeflow Pipelines` from Configurations Dropdown

### ISSUE THREAD

**Issue by ncbkr** [pluralsh/plural-artifacts#144]
## Summary

I want to give my notebook server access to Kubeflow Pipelines. I cannot select it from the dropdown. When I try to connect to the Pipelines API Server, I get status 500 and error message: "Internal error: Unauthenticated: Request header error: there is no user identity header".

## Reproduction

in Kubeflow, go to the notebooks webapp and try to check the "Allow access to Kubeflow Pipelines" option in the Configurations Dropdown

## Dagit UI/UX Issue Screenshots

![image](https://user-images.githubusercontent.com/70146154/152361358-d391845e-f838-4d96-bb13-6886bd61be38.png)

## Additional Info about Your Environment

Plural managed EKS cluster with Kubeflow

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by ncbkr** [comment]
The PodDefault resources in the user namespaces are missing. That's why it is not possible to select "Allow access to Kubeflow Pipelines"

```yaml
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: access-ml-pipeline
  namespace: <user-namespace>
spec:
  desc: Allow access to Kubeflow Pipelines
  env:
  - name: KF_PIPELINES_SA_TOKEN_PATH
    value: /var/run/secrets/kubeflow/pipelines/token
  selector:
    matchLabels:
      access-ml-pipeline: "true"
  volumeMounts:
  - mountPath: /var/run/secrets/kubeflow/pipelines
    name: volume-kf-pipeline-token
    readOnly: true
  volumes:
  - name: volume-kf-pipeline-token
    projected:
      sources:
      - serviceAccountToken:
          audience: pipelines.kubeflow.org
          expirationSeconds: 7200
          path: token
```
